"""Builds the ready-made word lists users can add in Settings → Word lists.

Each list lives in tools/packs/<id>/*.txt as "word=Farsi meaning" lines and is written to
js/data/packs/<id>.js. An index of all lists (name, description, size) goes to
js/data/packs/index.js, so the app can show them without downloading the words.

Phonetics come from the Oxford 5000 data when the word is there, otherwise from the CMU
Pronouncing Dictionary (multi-word entries such as phrasal verbs are joined word by word).

Usage:  python tools/build_packs.py
"""
import csv, glob, json, os, re

from build_words import ROOT, fetch, arpa_to_ipa

OUT = os.path.join(ROOT, '..', 'js', 'data', 'packs')

# Bump a list's version when its words change, so installed copies can offer the update.
PACKS = [
    {'id': 'gre', 'version': 1, 'name': 'GRE vocabulary',
     'description': 'High-frequency words from GRE verbal reasoning'},
    {'id': 'phrasal', 'version': 1, 'name': 'Phrasal verbs',
     'description': 'Everyday and academic phrasal verbs for speaking, listening and writing'},
]


def main():
    ox = {}
    for row in csv.DictReader(open(fetch('ox5000.csv'), encoding='utf-8')):
        ox.setdefault(row['word'].strip(), row['phon_n_am'].strip('/'))
    cmu = {}
    for line in open(fetch('cmudict.dict'), encoding='utf-8'):
        parts = line.split('#')[0].split()
        if parts and '(' not in parts[0]:
            cmu[parts[0]] = parts[1:]

    def ipa(word):
        if word in ox:
            return ox[word]
        parts = [p for p in re.split(r'[ -]', word) if p]
        if all(p.lower() in cmu for p in parts):
            return ' '.join(arpa_to_ipa(cmu[p.lower()]) for p in parts)
        return ''

    os.makedirs(OUT, exist_ok=True)
    index = []
    for pack in PACKS:
        words, seen = [], set()
        for f in sorted(glob.glob(os.path.join(ROOT, 'packs', pack['id'], '*.txt'))):
            for line in open(f, encoding='utf-8'):
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                w, _, fa = line.partition('=')
                w, fa = w.strip(), fa.strip()
                if not w or not fa or w.lower() in seen:
                    continue
                seen.add(w.lower())
                p = ipa(w)
                words.append([w, fa, p] if p else [w, fa])
        with open(os.path.join(OUT, pack['id'] + '.js'), 'w', encoding='utf-8', newline='\n') as f:
            f.write('// Generated by tools/build_packs.py. Do not edit by hand.\n')
            f.write('// [word, farsi, ipa]\n')
            f.write(f"export default {{ version: {pack['version']}, words: [\n")
            for r in words:
                f.write(json.dumps(r, ensure_ascii=False, separators=(',', ':')) + ',\n')
            f.write(']};\n')
        index.append({**pack, 'count': len(words)})
        missing = sum(1 for r in words if len(r) < 3)
        print(f"{pack['id']}: {len(words)} words ({missing} without phonetics)")

    with open(os.path.join(OUT, 'index.js'), 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Generated by tools/build_packs.py. Do not edit by hand.\n')
        f.write('export default ' + json.dumps(index, ensure_ascii=False, indent=2) + ';\n')


if __name__ == '__main__':
    main()
